version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Current directory:"
      - pwd
      - ls -la
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Checking jest binary..."
      - ls node_modules/.bin
      - echo "Running tests..."
      - ./node_modules/.bin/jest