version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Checking node_modules..."
      - ls -la node_modules/.bin || echo "node_modules missing"
      - echo "Running tests..."
      - npx jest